
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://discovery-service:8761/eureka
    instance:
      hostname: discovery-service

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9941
